version: '3' 
# apuntes 1 y comando: docker compose up -d
services:
  db:
    container_name: nestApp-db
    image: mongo:5.0.16
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    restart: always
